# Generated by Django 6.1.1 on 2026-10-03 03:11

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TotpDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("secret_encrypted", models.TextField(verbose_name="encrypted secret")),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                (
                    "last_step",
                    models.BigIntegerField(
                        default=0, verbose_name="last accepted step"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "authenticator app",
                "verbose_name_plural": "authenticator apps",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        max_length=400, unique=True, verbose_name="credential ID"
                    ),
                ),
                ("public_key", models.TextField(verbose_name="public key")),
                (
                    "sign_count",
                    models.BigIntegerField(default=0, verbose_name="signature counter"),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True, default=list, verbose_name="transports"
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(blank=True, max_length=64, verbose_name="AAGUID"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Passkey", max_length=120, verbose_name="name"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey",
                "verbose_name_plural": "passkeys",
                "ordering": ("-created_at",),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verify", "E-mail verification"),
                            ("login_2fa", "Two-step verification"),
                            ("password_reset", "Password reset"),
                            ("invite", "Workspace invitation"),
                        ],
                        max_length=32,
                        verbose_name="purpose",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=128, verbose_name="code hash"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="attempts"
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="consumed at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-mail code",
                "verbose_name_plural": "e-mail codes",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "purpose"],
                        name="tpsdk_accou_user_id_048f50_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mail address"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="token hash"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="accepted at"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["email", "accepted_at"],
                        name="tpsdk_accou_email_bb17e1_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=128, verbose_name="code hash"),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=8, verbose_name="prefix"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=120, verbose_name="label"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "recovery code",
                "verbose_name_plural": "recovery codes",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "used_at"],
                        name="tpsdk_accou_user_id_fc2432_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="token hash"
                    ),
                ),
                (
                    "device_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="device label"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "trusted device",
                "verbose_name_plural": "trusted devices",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="tpsdk_accou_user_id_05d060_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
