# Generated by Django 6.1.1 on 2026-10-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailgunConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Send e-mail through Mailgun.",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(blank=True, verbose_name="encrypted API key"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="For example: mg.example.com",
                        max_length=200,
                        verbose_name="sending domain",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("us", "United States"), ("eu", "Europe")],
                        default="us",
                        max_length=2,
                        verbose_name="region",
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="default sender address",
                    ),
                ),
                (
                    "default_from_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="default sender name"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "e-mail configuration (Mailgun)",
                "verbose_name_plural": "e-mail configuration (Mailgun)",
            },
        ),
    ]
