# Generated by Django 6.1.1 on 2026-10-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="provider"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Exact model name in the provider API.",
                        max_length=120,
                        verbose_name="identifier",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="label")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="One line on when to use this model.",
                        max_length=240,
                        verbose_name="description",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="One or two words about the model profile.",
                        max_length=40,
                        verbose_name="nickname",
                    ),
                ),
                (
                    "cost_tier",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Economy"), (2, "Balanced"), (3, "Premium")],
                        null=True,
                        verbose_name="cost tier",
                    ),
                ),
                (
                    "highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Shown as a card when choosing the model.",
                        verbose_name="highlighted",
                    ),
                ),
                (
                    "recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Gets the “Recommended” badge.",
                        verbose_name="recommended",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide the model without deleting it.",
                        verbose_name="active",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "supports_reasoning",
                    models.BooleanField(
                        default=False,
                        help_text="Reasoning models receive effort and never temperature. A wrong check makes the provider reject the call.",
                        verbose_name="supports reasoning",
                    ),
                ),
                (
                    "accepts_minimal_effort",
                    models.BooleanField(
                        default=True,
                        help_text="Unchecked sends “low” instead of “minimal”.",
                        verbose_name="accepts minimal effort",
                    ),
                ),
                (
                    "uses_thinking_budget",
                    models.BooleanField(
                        default=False,
                        help_text="The model takes a thinking token budget instead of an effort level (older Anthropic models).",
                        verbose_name="uses a thinking budget",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific call options (see the AI docs).",
                        verbose_name="provider options",
                    ),
                ),
                (
                    "input_price_usd_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="input price (USD/1M tokens)",
                    ),
                ),
                (
                    "cached_price_usd_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Empty uses the input price.",
                        max_digits=10,
                        null=True,
                        verbose_name="cached input price (USD/1M tokens)",
                    ),
                ),
                (
                    "output_price_usd_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="output price (USD/1M tokens)",
                    ),
                ),
                (
                    "prices_updated_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="prices updated on"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "AI model",
                "verbose_name_plural": "AI models",
                "ordering": ["provider", "order", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "identifier"), name="tpsdk_ai_model_unique"
                    )
                ],
            },
        ),
    ]
