# Generated by Django 6.1.1 on 2026-10-03 03:52

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Turns AI on for this workspace.",
                        verbose_name="enabled",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai", max_length=32, verbose_name="provider"
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifier of a catalog model of the chosen provider.",
                        max_length=120,
                        verbose_name="model",
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Inherit"),
                            ("minimal", "Minimal"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="default reasoning effort",
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="default maximum output tokens",
                    ),
                ),
                (
                    "daily_cap_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Once reached, no new run starts until the next day. Empty means no cap.",
                        max_digits=10,
                        null=True,
                        verbose_name="daily cap (USD)",
                    ),
                ),
                (
                    "store_content",
                    models.BooleanField(
                        default=True,
                        help_text="Store the prompt, input and output of each call. Off keeps only metrics (tokens, cost, latency).",
                        verbose_name="store event content",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="Event content older than this is purged; metrics stay. 0 keeps it forever.",
                        verbose_name="content retention (days)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "AI settings",
                "verbose_name_plural": "AI settings",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=240,
                        verbose_name="description",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("specialist", "Specialist"),
                            ("coordinator", "Coordinator"),
                        ],
                        db_index=True,
                        default="specialist",
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Identity and rules of the agent (a system prompt layer).",
                        verbose_name="instructions",
                    ),
                ),
                (
                    "input_template",
                    models.TextField(
                        default="{input}",
                        help_text="User message. Placeholders: {input} and {context}.",
                        verbose_name="input template",
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty inherits the model of the workspace settings.",
                        max_length=120,
                        verbose_name="model",
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Inherit"),
                            ("minimal", "Minimal"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="reasoning effort",
                    ),
                ),
                (
                    "verbosity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Inherit"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="verbosity",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sent only to models without reasoning.",
                        max_digits=3,
                        null=True,
                        verbose_name="temperature",
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum output tokens"
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Empty is free text. An object JSON Schema requires JSON.",
                        verbose_name="output schema",
                    ),
                ),
                (
                    "web_search",
                    models.BooleanField(
                        default=False,
                        help_text="The agent may search the web before answering.",
                        verbose_name="web search",
                    ),
                ),
                (
                    "web_search_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Only these sites (and subdomains). Empty means any site.",
                        verbose_name="web search domains",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent",
                "verbose_name_plural": "agents",
                "ordering": ["order", "name"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=240,
                        verbose_name="description",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Markdown. Used at runtime only after it is published.",
                        verbose_name="instructions (draft)",
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Overrides the agent's model while this skill is attached.",
                        max_length=120,
                        verbose_name="model",
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Inherit"),
                            ("minimal", "Minimal"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="reasoning effort",
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum output tokens"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
                "ordering": ["order", "name"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="A required skill without a published version makes the run fail; an optional one is skipped.",
                        verbose_name="required",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_skills",
                        to="tpsdk_ai.agent",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_agents",
                        to="tpsdk_ai.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "agent skill",
                "verbose_name_plural": "agent skills",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents",
                through="tpsdk_ai.AgentSkill",
                to="tpsdk_ai.skill",
            ),
        ),
        migrations.CreateModel(
            name="SkillVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="number")),
                ("instructions", models.TextField(verbose_name="instructions")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="note"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="published at"
                    ),
                ),
                (
                    "published_by_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="published by (name)",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="published by",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="tpsdk_ai.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "skill version",
                "verbose_name_plural": "skill versions",
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="skill",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tpsdk_ai.skillversion",
                verbose_name="published version",
            ),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="tpsdk_ai.agent",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tpsdk_ai.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="team",
            field=models.ManyToManyField(
                blank=True,
                related_name="coordinators",
                through="tpsdk_ai.TeamMember",
                through_fields=("coordinator", "specialist"),
                to="tpsdk_ai.agent",
            ),
        ),
        migrations.CreateModel(
            name="AIEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(db_index=True, verbose_name="execution"),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("specialist", "Specialist"),
                            ("consolidation", "Consolidation"),
                        ],
                        default="single",
                        max_length=16,
                        verbose_name="step",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="origin"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="reference",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        default="run", max_length=24, verbose_name="operation"
                    ),
                ),
                (
                    "agent_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="agent (name)",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(blank=True, default=list, verbose_name="skills"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="provider"
                    ),
                ),
                (
                    "model_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="requested model",
                    ),
                ),
                (
                    "responded_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="responding model",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        db_index=True,
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="HTTP"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=40,
                        verbose_name="error code",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="error message"
                    ),
                ),
                (
                    "error_detail",
                    models.TextField(
                        blank=True, default="", verbose_name="technical detail"
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="latency (ms)"
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="input tokens"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="output tokens"
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="total tokens"
                    ),
                ),
                (
                    "cached_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="cached tokens"
                    ),
                ),
                (
                    "reasoning_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="reasoning tokens"
                    ),
                ),
                (
                    "web_searches",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="web searches"
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="cost (USD)",
                    ),
                ),
                (
                    "input_price_usd_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="input price (USD/1M tokens)",
                    ),
                ),
                (
                    "output_price_usd_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="output price (USD/1M tokens)",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, default="", verbose_name="system prompt"
                    ),
                ),
                (
                    "input_text",
                    models.TextField(blank=True, default="", verbose_name="input"),
                ),
                (
                    "output_text",
                    models.TextField(blank=True, default="", verbose_name="output"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="raw response"
                    ),
                ),
                (
                    "user_label",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="user (name)"
                    ),
                ),
                (
                    "content_purged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="content purged at"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="tpsdk_ai.agent",
                        verbose_name="agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI event",
                "verbose_name_plural": "AI events",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["origin", "-created_at"], name="tpsdk_ai_ev_origin"
                    ),
                    models.Index(
                        fields=["agent", "-created_at"], name="tpsdk_ai_ev_agent"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="tpsdk_ai_ev_status"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="provider"
                    ),
                ),
                ("api_key_encrypted", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="added at"),
                ),
                (
                    "created_by_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="added by (name)",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="closed at"
                    ),
                ),
                (
                    "closed_by_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="closed by (name)",
                    ),
                ),
                (
                    "closed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deleted", "Deleted"),
                            ("replaced", "Replaced by a new key"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="reason",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="closed by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="added by",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI API key",
                "verbose_name_plural": "AI API keys",
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("closed_at__isnull", True)),
                        fields=("provider",),
                        name="tpsdk_ai_one_active_key_per_provider",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentskill",
            constraint=models.UniqueConstraint(
                fields=("agent", "skill"), name="tpsdk_ai_agent_skill_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="skillversion",
            constraint=models.UniqueConstraint(
                fields=("skill", "number"), name="tpsdk_ai_skill_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="tpsdk_ai_skill_name_unique_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("coordinator", "specialist"), name="tpsdk_ai_team_member_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("coordinator", models.F("specialist")), _negated=True
                ),
                name="tpsdk_ai_team_member_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="tpsdk_ai_agent_name_unique_alive",
            ),
        ),
    ]
