"""Envelope encryption of stored files.

The test that matters most is the plainest: what ``encrypt_stream`` returns
must NOT contain the original text. That check is what exposes providers whose
server-side encryption silently stores plaintext.
"""

from __future__ import annotations

import base64
import io
import os

from django.test import SimpleTestCase
import pytest

from tripaulx.storage import crypto
from tripaulx.storage.exceptions import StorageError

from .helpers import KEY, OTHER_KEY, override_tripaulx


def encrypt_bytes(data: bytes) -> bytes:
    return b"".join(crypto.encrypt_stream(io.BytesIO(data)))


def decrypt_bytes(data: bytes) -> bytes:
    return b"".join(crypto.decrypt_stream(io.BytesIO(data)))


class WithMasterKey(SimpleTestCase):
    """Base of the tests that need encryption ON.

    The override is entered in ``setUp`` rather than as a class decorator: the
    conftest blanks the key in a per-test fixture, and a class decorator would
    run BEFORE it and be overridden. Whoever applies last wins.
    """

    def setUp(self):
        super().setUp()
        self.enterContext(override_tripaulx(FILE_ENCRYPTION_KEY=KEY))


class EncryptionTests(WithMasterKey):
    """Round trip, and what the bucket sees."""

    def test_ciphertext_does_not_contain_the_original(self):
        secret = b"confidential: quarterly figures"

        out = encrypt_bytes(secret)

        self.assertNotIn(secret, out)
        self.assertNotIn(b"confidential", out)
        self.assertTrue(crypto.is_encrypted(out))

    def test_round_trip_returns_the_original(self):
        original = b"%PDF-1.4 document body"

        self.assertEqual(decrypt_bytes(encrypt_bytes(original)), original)

    def test_file_larger_than_one_chunk(self):
        # More than 1 MiB: exercises several chunks (index + last flag).
        original = os.urandom(crypto.CHUNK * 2 + 1234)

        self.assertEqual(decrypt_bytes(encrypt_bytes(original)), original)

    def test_two_uploads_of_the_same_file_differ(self):
        # Fresh key and nonce per upload: otherwise equal files would have equal
        # bytes in the bucket, and an observer would learn something.
        data = b"same content"

        self.assertNotEqual(encrypt_bytes(data), encrypt_bytes(data))

    def test_empty_file_is_refused(self):
        with pytest.raises(StorageError):
            encrypt_bytes(b"")


class IntegrityTests(WithMasterKey):
    """Tampering with the object must FAIL, never return silent garbage."""

    def test_flipped_byte_fails(self):
        out = bytearray(encrypt_bytes(b"important content"))
        out[-1] ^= 0x01  # last byte (inside the tag/ciphertext)

        with pytest.raises(StorageError, match="tampered|corrupted"):
            decrypt_bytes(bytes(out))

    def test_truncated_file_fails_instead_of_returning_half(self):
        # A cut object has no chunk flagged as LAST. Returning what is there
        # would be worse than failing: half a document passed off as whole.
        whole = encrypt_bytes(os.urandom(crypto.CHUNK * 2))

        with pytest.raises(StorageError, match="truncated|corrupted"):
            decrypt_bytes(whole[: len(whole) // 2])

    def test_wrong_master_key_does_not_decrypt(self):
        out = encrypt_bytes(b"secret")

        with override_tripaulx(FILE_ENCRYPTION_KEY=OTHER_KEY):
            with pytest.raises(StorageError, match="master key"):
                decrypt_bytes(out)

    def test_plaintext_object_is_not_taken_for_encrypted(self):
        # An object stored in clear has no marker; decrypting it raises
        # instead of returning noise.
        clear = b"%PDF-1.4 a file stored in clear in the bucket" * 3

        with pytest.raises(StorageError, match="encrypted format"):
            decrypt_bytes(clear)


class MasterKeyTests(SimpleTestCase):
    """The master key: missing, malformed, and generated by the command."""

    def test_without_a_key_encryption_is_off(self):
        self.assertFalse(crypto.encryption_enabled())
        with pytest.raises(StorageError, match="FILE_ENCRYPTION_KEY"):
            encrypt_bytes(b"hi")

    def test_key_of_the_wrong_size_is_refused_with_a_message(self):
        short = base64.urlsafe_b64encode(b"short").decode()
        with override_tripaulx(FILE_ENCRYPTION_KEY=short):
            with pytest.raises(StorageError, match="32 bytes"):
                encrypt_bytes(b"hi")

    def test_key_that_is_not_base64_is_refused(self):
        with override_tripaulx(FILE_ENCRYPTION_KEY="not base64!"):
            with pytest.raises(StorageError, match="base64"):
                encrypt_bytes(b"hi")

    def test_generated_key_works(self):
        new = crypto.generate_master_key()

        with override_tripaulx(FILE_ENCRYPTION_KEY=new):
            self.assertEqual(decrypt_bytes(encrypt_bytes(b"ok")), b"ok")

    def test_magic_header_is_neutral_and_versioned(self):
        self.assertEqual(crypto.MAGIC, b"TPX1\x00")
